app_home_index:
    path:     /
    defaults: { _controller: AppBundle:Home:index }

app_home_contact:
    path:     /contact/
    defaults: { _controller: AppBundle:Home:contact }

app_home_cost:
    path:     /cost/
    defaults: { _controller: AppBundle:Home:cost }
